### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by eliaskalach** [janpie/roi-dapps-calculator#1]
I am trying to run on Windows 11 X64 after installing JRE 1.8 but I am getting an exception error 

Exception in thread "main" org.openqa.selenium.TimeoutException: Expected condition failed: waiting for pages.BasePage$$Lambda$280/0x0000000800dc39a0@24fb6a80 (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: 'unknown', revision: 'unknown', time: 'unknown
![Screenshot 2022-03-30 145930](https://user-images.githubusercontent.com/831843/160832522-c5e1aacd-587a-4e7a-8d1e-1cbe7c69f7b7.png)
'

**Comment by janpie** [comment]
Hi,
Can you paste your config.json file?

**Comment by eliaskalach** [comment]
yes sure,,,,here it is

{
  "chain": "AVALANCHE",
  "contractAddress": "0x31D12F45Dc75aF5a71A295bc172bed8fD7a13BBC",
  "devFee": 10,
  "plans": [
    {
      "days": 14,
      "totalReturn": 112,
      "withdrawalFee": 10
    },
    {
      "days": 21,
      "totalReturn": 137,
      "withdrawalFee": 10
    },
    {
      "days": 28,
      "totalReturn": 140,
      "withdrawalFee": 10
    },
    {
      "days": 14,
      "totalReturn": 194,
      "withdrawalFee": 10
    },
    {
      "days": 21,
      "totalReturn": 275,
      "withdrawalFee": 10
    },
    {
      "days": 28,
      "totalReturn": 292,
      "withdrawalFee": 10
    }
  ]
}
[config.txt](https://github.com/janpie/roi-dapps-calculator/files/8380379/config.txt)

**Comment by janpie** [comment]
The bug is fixed you can redownload/pull the repo

**Comment by eliaskalach** [comment]
OK,  I'll try it and let you know

Thank you for the nice work and novel idea,
Will you continue with such projects?
